### ISSUE TITLE
Missing hosts

### ISSUE THREAD

**Issue by ffs97** [4skinSkywalker/Anti-Porn-HOSTS-File#15]
Hi! Great work with this file. Thanks a lot.

There are a few missing hosts and I am sure the list will keep on expanding forever. My suggestion is to have an open issue where people can comment on missing hosts?

Anyway, these 2 hosts are missing
- 4porn.com
- nhentai.com

In case you want me to send a pull request, let me know. Again, thanks a lot for the great work.

**Comment by 4skinSkywalker** [comment]
Added!

**Comment by daisybrain** [comment]
Take notice that some pornsites are still avaliable through national domains, for example xhamster.la

**Comment by daisybrain** [comment]
At the same time  pozdrawleniya.com and pozdrawleniya.ru look neither like a pornsites nor like an ad network. I suppose there are more such mistakenly added instances in the list.

**Comment by 4skinSkywalker** [comment]
> At the same time pozdrawleniya.com and pozdrawleniya.ru look neither like a pornsites nor like an ad network. I suppose there are more such mistakenly added instances in the list.

I've translated it in Italian and at the bottom of the page I read something like "Beautiful girls and naked women at home" with a link that brings to erotag.com. I won't remove this garbage from the list. Sorry

![image](https://user-images.githubusercontent.com/17194393/95129688-a6fdc780-075b-11eb-985c-1938870567eb.png)
![image](https://user-images.githubusercontent.com/17194393/95129872-f17f4400-075b-11eb-854f-6f298d9e7f69.png)
![image](https://user-images.githubusercontent.com/17194393/95129913-05c34100-075c-11eb-92ce-190680747b13.png)

**Comment by ffs97** [comment]
On the same note, menshealth and womenshealth are banned. Even though there are posts on these websites that relay sexual education, this is not porn. I do not think these should be part of the list.

**Comment by se7enge** [comment]
Hi friend,

None of the following websites are on the list. All of them contain pornographic content, or content that directly advertises/leads to pornographic content. I also include tinder and instagram in my own list but I realise that may be a little extreme for some.

thots.tv
dirtyship.com
directorysex.com
thothub.live
thothub.ru
thotbook.tv
thothub.wtf
thepornlinks.com
nsfwthots.blogspot.com
sexy-egirls.com
viralporn.com
snaggys.com
nudes7.com
cloudisexy.com
imagefap.com
camwhoresbay.com
moresisek.org
creative.smljmp.com
camwhoreshd.com
xx-xgirls.info
pussy-hub.com
watch.porn
k2s.club
adult-channels.com
vip-pussy.com
cambabe.video
fapdick.net
xfantazy.com
biqle.com
porn-asmr.com
asmrxxx.com
pornado.co
slutpad.com
eroasmr.com
pornhat.tv
momvids.com
asmrx365.com
sexy-asmr.com
asmrporntube.com
sexcelebrity.net
asmrlust.com
porndollz.com
secure.adultfriendfinder.com

**Comment by 4skinSkywalker** [comment]
> Hi friend,
> 
> None of the following websites are on the list. All of them contain pornographic content, or content that directly advertises/leads to pornographic content. I also include tinder and instagram in my own list but I realise that may be a little extreme for some.
> 
> Click to expand
> thots.tv
> dirtyship.com
> directorysex.com
> thothub.live
> thothub.ru
> thotbook.tv
> thothub.wtf
> thepornlinks.com
> nsfwthots.blogspot.com
> sexy-egirls.com
> viralporn.com
> snaggys.com
> nudes7.com
> cloudisexy.com
> imagefap.com
> camwhoresbay.com
> moresisek.org
> creative.smljmp.com
> camwhoreshd.com
> xx-xgirls.info
> pussy-hub.com
> watch.porn
> k2s.club
> adult-channels.com
> vip-pussy.com
> cambabe.video
> fapdick.net
> xfantazy.com
> biqle.com
> porn-asmr.com
> asmrxxx.com
> pornado.co
> slutpad.com
> eroasmr.com
> pornhat.tv
> momvids.com
> asmrx365.com
> sexy-asmr.com
> asmrporntube.com
> sexcelebrity.net
> asmrlust.com
> porndollz.com
> secure.adultfriendfinder.com
> 
> Hope this helps :)

Yes, it helped! Thanks 💯

**Comment by nofapcontributor** [comment]
Thanks for this project! Let me contribute with some more websites, mainly from central Europe. Please check or help me to understand which format of URL is right, cuz I'm having a problem with blocking pornuj.cz even when it's in the host file.
0.0.0.0       https://fapdungeon.com/
0.0.0.0       https://www.pornuj.cz/
0.0.0.0       https://ceske-kundy.cz/
0.0.0.0       https://pornovka.cz/
0.0.0.0       https://pornujzdarma.cz/
0.0.0.0       https://nejlepsipecko.cz/
0.0.0.0       https://pornoland.cz/
0.0.0.0       https://freevideo.cz/
0.0.0.0       https://tube4world.com/
0.0.0.0       https://coolporno.cz/
0.0.0.0       http://www.dlouha-videa.eu/
0.0.0.0       https://www.pornofile.cz/
0.0.0.0       https://zvraceny.cz/
0.0.0.0       https://www.lxxlxx.com/
0.0.0.0       https://freepornq.com/
0.0.0.0       http://www.crabporn.com/
0.0.0.0       https://ceske-porno-filmy.cz/
0.0.0.0       https://www.hdporno.sk/
0.0.0.0       https://xpornuj.cz/
0.0.0.0       http://tubyrose.com/
0.0.0.0       http://tubegold.xxx/
0.0.0.0       https://pornonamobil.cz/
0.0.0.0       https://www.ceskepornoherecky.cz/
0.0.0.0       https://www.najporno.sk/ceske-porno/
0.0.0.0       https://zaprachy.eu/
0.0.0.0       http://dameporno.cz/
0.0.0.0       http://www.way.xxx/

**Comment by nofapcontributor** [comment]
Some more.
0.0.0.0       zoozootube.com
0.0.0.0       zooredtube.com
0.0.0.0       xxxvideoszoo.com
0.0.0.0       zooyouporn.com
0.0.0.0       zoosex.me
0.0.0.0       dogporntube.siteen
0.0.0.0       animalsex.party
0.0.0.0       www.kinky-porn.net
0.0.0.0       www.kinkyteenporn.com
0.0.0.0       www.filthnest.com
0.0.0.0       thebestfetishsites.com
0.0.0.0       kinkygonzo.com
0.0.0.0       18andabused.pro
0.0.0.0       xxnx.name
0.0.0.0       xxxomg.com
0.0.0.0       www.fapcat.com
0.0.0.0       pornbaker.com
0.0.0.0       www.sofcams.com
0.0.0.0       www.jerkmatelive.org
0.0.0.0       bimbim.com
0.0.0.0       thepornlistlive.com
0.0.0.0       xlovefetish.com
0.0.0.0       www.secretfriends.com
0.0.0.0       www.slutroulettelive.org
0.0.0.0       lp.puretaboo.com
0.0.0.0       tour1.21sextreme.com
0.0.0.0       www.lookathernow.com
0.0.0.0       www.outofthefamily.com
0.0.0.0       landing.recklessinmiami.com
0.0.0.0       recklessinmiami.com
0.0.0.0       88fuck.com
0.0.0.0       www.freudbox.com
0.0.0.0       yourlustmovies.com
0.0.0.0       www.watchmygf.xxx
0.0.0.0       myxvids.com
0.0.0.0       voyeurboss.com
0.0.0.0       89.com
0.0.0.0       toppornsites.net
0.0.0.0       www.puretaboo.com
0.0.0.0       pornworld.com
0.0.0.0       www.thenude.com
0.0.0.0       hentaikey.com
0.0.0.0       www.pornflip.com
0.0.0.0       www.al4a.com
0.0.0.0       arabsex1.com
0.0.0.0       www.teasepov.com
0.0.0.0       povd.com
0.0.0.0       www.joylovedolls.com
0.0.0.0       www.yourdoll.com
0.0.0.0       juicygif.com
0.0.0.0       www.famedigital.com
0.0.0.0       landing.mofosnetwork.com
0.0.0.0       mofosnetwork.com
0.0.0.0       www.xempire.com
0.0.0.0       rankedpornsites.com
0.0.0.0       www.thepornblender.com
0.0.0.0       mypornadviser.com
0.0.0.0       www.famedigital.com
0.0.0.0       toppornguide.com
0.0.0.0       landing.trueamateurs.com
0.0.0.0       trueamateurs.com
0.0.0.0       www.karupsha.com
0.0.0.0       18exgfs.com
0.0.0.0       landing.sweetsinner.com
0.0.0.0       sweetsinner.com
0.0.0.0       www.devilsfilm.com
0.0.0.0       nastypornpics.com
0.0.0.0       www.azpornpics.com
0.0.0.0       jerkdolls.com
0.0.0.0       www.tsplayground.com

**Comment by 4skinSkywalker** [comment]
@nofapcontributor you shouldn't prefix with http:// and you should insert both www and non-www versions.

**Comment by justrandompost** [comment]
Some hosts that have gone through my version of this file + Umbrella + Firefox
www.ceskeporno.sk
ceske-kundy.cz
freevideo.eu
porno-zdarma.com
pornovideo.sk
www.pornohdcz.com

**Comment by se7enge** [comment]
Hello again,

Got some more missing urls which I have already added on my end.

<details><summary>Click to expand</summary><p>

0.0.0.0       asmrsex.com
0.0.0.0       porntn.com
0.0.0.0       asmrxxx.com
0.0.0.0       porn-asmr.com
0.0.0.0       xnimo.com
0.0.0.0       sexy-asmr.com
0.0.0.0       sluttish.us
0.0.0.0       grannymommy.com
0.0.0.0       sex-libre.org
0.0.0.0       asstoo.com
0.0.0.0       gotanynudes.com
0.0.0.0       onlyfansleak.biz
0.0.0.0       xtokk.com
0.0.0.0       amateurscrush.com
0.0.0.0       thegirlgirl.com
0.0.0.0       youngteenpussy.com
0.0.0.0       xxxvideos247.com
0.0.0.0       hardpole.com
0.0.0.0       cambro.tv
0.0.0.0       pornlift.com
0.0.0.0       xxxclipsex.com
0.0.0.0       leaknudes.com
0.0.0.0       pornmega.com
0.0.0.0       spankingtube.com
0.0.0.0       niceporn.tv
0.0.0.0       nastyvideotube.com
0.0.0.0       cumingtube.com
0.0.0.0       4xxxvideos.com
0.0.0.0       sexmotors.com
0.0.0.0       daily-bbw-porn.com
0.0.0.0       celebritykink.com
0.0.0.0       linkshit.com
0.0.0.0       prothots.com
0.0.0.0       allporn.xyz
0.0.0.0       coedporn.xyz
0.0.0.0       forhertube.xyz
0.0.0.0       leakedamateurporn.xyz
0.0.0.0       folieporno.xyz
0.0.0.0       nurxxx.xyz
0.0.0.0       tukif.xyz
0.0.0.0       yourjoyporn.xyz
0.0.0.0       alohatube.xyz
0.0.0.0       streamingporn.xyz

**Comment by loquesangra** [comment]
0.0.0.0 rule34.world

**Comment by iam-py-test** [comment]
@nofapcontributor @justrandompost  please edit your comments so the domains are not auto-linked.

**Comment by 4skinSkywalker** [comment]
@nofapcontributor @se7enge I've added your entries in commit 11e77fd07c8fff17dcc083dd17e79cb68e1089fc

**Comment by SkrudjReal** [comment]
0.0.0.0 pornokaef.tv

**Comment by DNDEBUG** [comment]
add my list too
https://github.com/1boii/hosts/issues/1

**Comment by whitenight1337** [comment]
Please add 
0.0.0.0 nsfwmonster
Appreciate it

**Comment by DNDEBUG** [comment]
> Please add 0.0.0.0 nsfwmonster Appreciate it

nsfwmonster what? .com? .net?

**Comment by whitenight1337** [comment]
> > Please add 0.0.0.0 nsfwmonster Appreciate it
> 
> nsfwmonster what? .com? .net?

Sorry, nsfwmonster.com my bad

**Comment by DNDEBUG** [comment]
thanks

**Comment by 4skinSkywalker** [comment]
Would you guys like to have a UI with which you can submit new domains (and maybe check pending ones)? The idea is that each end of the month I take all the domains submitted and integrate them into the HOSTS file.

**Comment by DNDEBUG** [comment]
you can take from my hosts files
if you want, take only the ones with # OK on the adult list
the other lists are small and have been reviewed

**Comment by 4skinSkywalker** [comment]
@DNDEBUG I've just added the # OK entries of your hosts: 06438118c3cca15b611c9394f1cbf53c6c6417b9.

**Comment by 4skinSkywalker** [comment]
Guys I'm opening a new issue for missing hosts with a brief explainer on how to make collapsible section.
