### ISSUE TITLE
Breaks ad.doubleclick.net redirects

### ISSUE THREAD

**Issue by wearefalling** [4skinSkywalker/anti-porn-hosts-file#2]
### Description
Since ad.doubleclick.net is blocked by this hosts file.

### Example URL
I had to break in into two since github seems to block Doubleclick links..

Domain: https://ad.doubleclick.net
Path: /ddm/clk/427816977;229804046;v?https://www.netonnet.se/art/fyndvaror/ljud-och-bild/tv-och-bild-tillbehr/nedis-x-ersattningsfjarrkontroll-for-samsung-tv/X1006614.4815

**Comment by 4skinSkywalker** [comment]
Do you suggest to remove ad.doubleclick.net from the file?
