### ISSUE TITLE
not working at all

### ISSUE THREAD

**Issue by cosg2002** [4skinSkywalker/anti-porn-hosts-file#20]
Hi. I pasted this into my hosts file, saved, closed it, rebooted my PC, and then tried to go to www.pornhub.com. To my surprise, I was able to connect to the site with no issues despite it being listed in the hosts file. I am completely lost as to how this is possible

**Comment by jpenguin** [comment]
What OS/browser?  You may need https://www.wikihow.com/Flush-DNS

**Comment by 4skinSkywalker** [comment]
> Hi. I pasted this into my hosts file, saved, closed it, rebooted my PC, and then tried to go to [www.pornhub.com](http://www.pornhub.com). To my surprise, I was able to connect to the site with no issues despite it being listed in the hosts file. I am completely lost as to how this is possible

Give us a bit more details please. Re-open your hosts file and check if records are still there, you may need to read and write the file with administrator privileges.

**Comment by cosg2002** [comment]
I attempted with administrator priveleges and it does not work.

Here is my strategy with this. I created a new windows 10 profile and set up the access so that this profile is the only one that can access the hosts file and edit it. I opened notepad in administrator and opened the hosts file on all my drives, pasted the list in, rebooted, made sure it actually updated, and it still does not work.

**Comment by cosg2002** [comment]
It ended up being an issue with permissions. You have to give "Users" the ability to read/execute the hosts file in order for it to function properly. My bad
