### ISSUE TITLE
Breaks anonym.to redirects

### ISSUE THREAD

**Issue by wearefalling** [4skinSkywalker/anti-porn-hosts-file#3]
### Description
Since anonym.to is blocked by this hosts file.

### Example URL

1. https://anonym.to/?https://github.com/4skinSkywalker/anti-porn-hosts-file/issues/
2. https://anonym.to/?https://www.lifewire.com/legalities-of-linking-3468972

**Comment by 4skinSkywalker** [comment]
Do you suggest to remove anonym.to from the file?
