### ISSUE TITLE
No variants on host names

### ISSUE THREAD

**Issue by Sairith15029** [4skinSkywalker/Anti-Porn-HOSTS-File#31]
Currently, there are no duplicates for formatting changes that can be used to bypass the host file block. For example:

-website.com
-http://website.com
-https://website.com
-www.website.com
-http://www.website.com
-https://www.website.com

I'm sure that there's a way to automatically add in the mutations of each individual address, I'm just not sure how off the top of my head.

**Comment by 4skinSkywalker** [comment]
On my computer if website.com is blocked then I'm unable to access the prefixed version with http and https yet I could access www.website.com if not explicitly added. That's why when I add sites I put the www and non-www versions.
