### ISSUE TITLE
No Proxy sites added

### ISSUE THREAD

**Issue by bluemilk00** [4skinSkywalker/Anti-Porn-HOSTS-File#32]
Porn can still be accessed from using proxy sites like hide.me and proxysite.com

**Comment by 4skinSkywalker** [comment]
You could add those to the file.

By the way, porn can also still be accessed by not using this file at all. -_-

This file is not meant to block your free will, but to make watching porns more difficult and feel like you'll act against your will by forcing the mechanism you set in place.
