### ISSUE TITLE
Wrongly added

### ISSUE THREAD

**Issue by justrandompost** [4skinSkywalker/Anti-Porn-HOSTS-File#34]
The site zverokruh seems legit, I suppose they just sell food for animal.

**Comment by 4skinSkywalker** [comment]
I bet there are more legit sites on the list as it was firstly derived by a merge with the most reknown anti-porn hosts. I hope that with a community effort we can remove those legit sites and increase the bad ones. Thanks

**Comment by justrandompost** [comment]
The zverokruh site is removed in #36
