### ISSUE TITLE
Google is blocked

### ISSUE THREAD

**Issue by Ambyjkl** [4skinSkywalker/Anti-Porn-HOSTS-File#35]
The most recent commit blocks google

**Comment by justrandompost** [comment]
Sorry for that. It should be solved with #36 .

**Comment by justrandompost** [comment]
@4skinSkywalker Had already solved it few minutes before me. This issue is ready to close.

**Comment by 4skinSkywalker** [comment]
Yeah, I just removed that as soon as I've seen the message by @Ambyjkl.
Thanks guys! 💯
