### ISSUE TITLE
Creating a software to block websites  

### ISSUE THREAD

**Issue by khaldon** [4skinSkywalker/Anti-Porn-HOSTS-File#43]
what if we create a software like a extensions in browsers or application mobile to block all data we have collected it until now ? because blocking with Hosts file it's not affective.

**Comment by 4skinSkywalker** [comment]
Blocking hosts file is effective as long as you keep it your file up to date. I think that a browser extension that automatically download the file from this repo and blocks porn site on the browser is a pretty good idea! Even cooler if users can use that extension to mark new porn sites. I'm taking notes ;)

**Comment by soystemd** [comment]
[uBlock](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/) [Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en) is probably what you are looking for. You can add any hosts files in it's settings, and it keeps them up to date and all. You can manually block or allow individual websites as well.

For Linux there is [hblock](https://github.com/hectorm/hblock), which also allows you to manually add or remove individual websites from the hosts files.

For Windows, you can use [StevenBlack's scripts](https://github.com/StevenBlack/hosts#how-do-i-control-which-sources-are-unified) to keep your hosts files up to date. You can add links of more hosts files to the `data/` folder, as explained in the README.

And for Andoid, you can use either Firefox mobile with uBlock Origin addon ([Google Play link](https://play.google.com/store/apps/details?id=org.mozilla.firefox&hl=en&gl=US)) , or [AdAway](https://github.com/AdAway/AdAway).

**Comment by 4skinSkywalker** [comment]
@soystemd said it all. Closing this
