### ISSUE TITLE
Amazon.com is blocked?

### ISSUE THREAD

**Issue by BrickTheNick** [4skinSkywalker/Anti-Porn-HOSTS-File#44]
Any reason amazon.com is blocked? I removed everything from the list with "amazon" in the name but that doesn't fix the problem.

**Comment by 4skinSkywalker** [comment]
Nope it's not. I just tried.

**Comment by BrickTheNick** [comment]
Interesting, it absolutely was for me, and reverting to my original hosts file completely fixed it. Looks like I will have to use a different solution.
