### ISSUE TITLE
The PIrate Bay listed as a site

### ISSUE THREAD

**Issue by CarrotIsACarrot** [4skinSkywalker/Anti-Porn-HOSTS-File#51]
New to github, so formatting might be terrible.
thepiratebay.org is listed as a porn site, even though its just a list of torrents. Sure, you could find porn, but you can do that on twitter and reddit and google too. I'm just trying to pirate some stuff here!

**Comment by 4skinSkywalker** [comment]
Well do you feel like PRing the changes you see fit? :)

**Comment by CarrotIsACarrot** [comment]
bro i have never actually used github in my life i have no idea how to do that

**Comment by 4skinSkywalker** [comment]
No problem.
3d6d8a2 is the hash of the commit!
Thank you. :)
