### ISSUE TITLE
Steven black, Andrew Black, and Eric Roberts (Blackout)

### ISSUE THREAD

**Issue by Nimotaj** [4skinSkywalker/Anti-Porn-HOSTS-File#57]
The men listed above have been secretly live streaming me and my mother inside our homes without our consent. If anyone can help please send all  information on Steven black to me please. These men and there family have destroyed my life with this porn we did not consent to any of this. They have stolen privacy and peace from my family. In our home city he uses women and children to follow us around to record for there live stream all Without consent.... PLEASE HELP US STOP STEVEN BLACK

**Comment by 4skinSkywalker** [comment]
I'm closing this shit.
