### ISSUE TITLE
VLC website blocked

### ISSUE THREAD

**Issue by PseudoTemporaire** [4skinSkywalker/Anti-Porn-HOSTS-File#61]
Hey, your work is awesome ! using it on my raspberry pi dns :D
But i found that the hostnames "videolan.org" and "www.videolan.org" are figuring in this file.
So the website of VLC is not accessible :/
Can you fix it please ?
Thanks 👍🏻

**Comment by 4skinSkywalker** [comment]
Solve in 5c4677620a739c818b3cbc273c2fb9d2fd4a9d00
Thank you! 👯
