### ISSUE TITLE
(Question) Why are image services blocked? (ie: imgur, imgbox)

### ISSUE THREAD

**Issue by badlydrawnface** [4skinSkywalker/Anti-Porn-HOSTS-File#62]
I wonder why imgur is blocked on this host file, I use it for controller overlays for streams, and I can't seem to willing find porn on the site, I would assume you would have to go out of your way to create an account to find any pornography on that site, so I don't know why its on this list,

I was just wondering whether or not it was intentional to add imgur. I personally removed it from my hosts file. I submitted PR #63 that removes it.

**Comment by 4skinSkywalker** [comment]
Thank you! :D
