### ISSUE TITLE
invalid domains

### ISSUE THREAD

**Issue by Ash3781** [4skinSkywalker/Anti-Porn-HOSTS-File#92]
hey, when updating gravity for pihole, it gives me this:
```
Sample of non-domain entries:
- "www.سكس.cc"
- "www.افلام-سكس.com"
- "www.xvideos-español.com"
- "xvideos-español.com"
```
could you remove these?

**Comment by 4skinSkywalker** [comment]
@Ash3781 Yeah sure, indeed they are invalid domain entries. Tomorrow after merging the two PRs I'll remove them :)

**Comment by Ash3781** [comment]
Tha k you for the quick fix, keep up the good work :3

**Comment by 4skinSkywalker** [comment]
Said domains were removed successfully! Thank you
