### ISSUE TITLE
Remove pivix.com

### ISSUE THREAD

**Issue by sefinek24** [4skinSkywalker/Anti-Porn-HOSTS-File#94]
its false positive imo

The Pixiv website doesn't solely focus on NSFW content

**Comment by sefinek24** [comment]
#95

**Comment by sefinek24** [comment]
@4skinSkywalker and `www.reddit.com`

**Comment by sefinek24** [comment]
@4skinSkywalker `www.gog.com` & `gog.com`

**Comment by tamas646** [comment]
Please do not ping people. Just write your suggestions, someone will make a pull request when he/she has time. Pinging doesn't speed up the process.

I included your changes from #95 in my pull request #96 . You can delete your pull request now as its not needed anymore.
Thanks for the contribution. :)

**Comment by 4skinSkywalker** [comment]
@sefinek24 @tamas646 thank you guys!
